### PR TITLE
FIX: correct previous recon-all reporting

### PR DESCRIPTION
**Pull request by mgxd**
Closes https://github.com/poldracklab/fmriprep/issues/2049

Turns out we weren't passing in the `sub-` identifier, which in turn made ReconAll (rightfully) assume the subject wasn't run.

This also imports the modified `ReconAll` interface used in smriprep.

### CODE REVIEW

**Comment by effigies** [comment]
Issue introduced in https://github.com/nipreps/niworkflows/pull/299, released in niworkflows 0.7.0, and thus affecting fMRIPrep 1.3.0+.

Can you target `maint/20.0.x`, and then we can just merge this forward?

**Comment by mgxd** [comment]
untangling some more webs:

```python
In [1]: from smriprep.interfaces import freesurfer as fs                                                                                                                          
In [2]: fs.ReconAll                                                                                                                                                               
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-53ff371892c6> in <module>
----> 1 fs.ReconAll

AttributeError: module 'niworkflows.interfaces.freesurfer' has no attribute 'ReconAll'

In [3]: from smriprep.interfaces.freesurfer import ReconAll
In [4]: exit
```

this seems hazardous given `smriprep.interfaces.freesurfer` exists..

**Comment by effigies** [comment]
Ugh. That's a nasty one.

File: fmriprep/interfaces/reports.py [hunk 1]
```diff
@@ -16,7 +16,7 @@
     traits, TraitedSpec, BaseInterfaceInputSpec,
     File, Directory, InputMultiObject, Str, isdefined,
     SimpleInterface)
-from nipype.interfaces import freesurfer as fs
+from smriprep.interfaces.freesurfer import ReconAll
```
Comment (effigies) [inline fmriprep/interfaces/reports.py:19]: I'm not actually sure we need that. All that patch allows us to do is to specify a collection of `steps` instead of a `directive`. We are testing the directive `all` below.

Comment (mgxd) [reply fmriprep/interfaces/reports.py:19]: i added that import to keep the `recon-all` calls consistent - lmk if you feel strongly to change that

Comment (effigies) [reply fmriprep/interfaces/reports.py:19]: I don't feel strongly.

**Comment by mgxd** [comment]
before:
https://13616-53175327-gh.circle-artifacts.com/0/tmp/ds005/derivatives/fmriprep/sub-01.html

after:
https://13789-53175327-gh.circle-artifacts.com/0/tmp/ds005/derivatives/fmriprep/sub-01.html#Summary
