### ISSUE TITLE
Preprocessing Error

### ISSUE THREAD

**Issue by AzmatUllahKhan** [poldracklab/fmriprep#1117]
I ran fmriprep on valid BIDS dataset but i am getting the following error. Any idea what is causing the error.

$ fmriprep BIDS_NKI/Nifti/ preprocessed/ sub-01 -w work/

/home/azmat/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/azmat/.local/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/home/azmat/.local/lib/python2.7/site-packages/fmriprep/cli/run.py", line 216, in main
    from multiprocessing import set_start_method, Process, Manager
ImportError: cannot import name set_start_method

**Comment by effigies** [comment]
I suspect this is a Python 3-only function. fMRIPrep does not support Python 2.

We recommend using either Docker or Singularity to run fMRIPrep (see [Installation](https://fmriprep.readthedocs.io/en/latest/installation.html)). If you want to run locally, I personally recommend using the [Anaconda](https://www.anaconda.com/download/) distribution to set up independent environments.

**Comment by effigies** [comment]
> Thankyou so much. what should i write in the participant option in below command?
> $ fmriprep-docker /path/to/data/dir /path/to/output/dir participant

`participant` is a processing level indicator, and fMRIPrep only supports the `participant` level right now. So the command you have there is fine. You may want to add `--participant-label <label>` to indicate a subset of participants to process at a time.

**Comment by oesteban** [comment]
@AzmatUllahKhan, `multiprocessing.set_start_method` was introduced in Python 3.4, so you can try the `fmriprep-docker` option or updating your environment to Python>=3.5 (some other bits of FMRIPREP will not work with python 3.4).
